index:
    path: /
    controller: App\Controller\DefaultController::index
categories:
    path: /categories
    controller: App\Controller\CategoryController::index
category:
    path: /categories/{slug}
    controller: App\Controller\CategoryController::show